# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a17a29aba86f2ef241f9e8d88dbfc5e7bad9780c20f6693fa8e88ea2e924f67bf78d3679e667eedceed15df5137a52d3e51c10a767a3d8bed49360d1621a16a8

test:
  secret_key_base: 13c4c701d6e3fe17b0f5a81d9e9bb4884115903403eba5dda285374c4b424667c43719cd9d7f8b74073600f3db0cab850a845279223dd054a8f48278f99d3ad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
